include:
  - project: 'platform/re-team/fly-pipeline'
    ref: 'main'
    file: '.main.ci.yaml'


variables:
  REGISTRY_IMAGE: "gitlab.samoletgroup.ru:5000/cits/ithub/metamodel"
  KUBE_NAMESPACE: ithub
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: 0
  SINGLE_DEPLOY: "true"
  ITHUB_DOMAIN_STAGE: https://ithub-stage.samoletgroup.ru
  ITHUB_DOMAIN_PROD: https://ithub.samoletgroup.ru
  

reload backend stg:
  stage: post-deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(release|hotfix|trunk)\/.+$/'
  trigger:
    project: cits/ithub/warmer
    branch: stage


reload backend prod:
  stage: post-deploy
  rules:
    - if: $CI_COMMIT_TAG
  trigger:
    project: cits/ithub/warmer
    branch: prod


create image:
  variables:
    BUILD_ARGS: >-
      --build-arg RELEASE_VERSION=${CI_COMMIT_REF_NAME}


deploy stg:
  when: on_success


switch stg:
  when: on_success


ready to prod:
  when: on_success


deploy prod:
  when: on_success


close release:
  when: on_success
