version: '3.3'

services:
  plantuml-server:
    build:
      context: .
      dockerfile: Dockerfile.jetty
    # image: plantuml/plantuml-server:jetty-local
    image: mumg/plantuml-elk:latest    
    container_name: plantuml-server
    ports:
      - 9000:8080
    environment:
      - BASE_URL=plantuml